<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>dev.lokspel</groupId>
  <artifactId>ZonePracOldCombat</artifactId>
  <version>1.0.1</version>
  <packaging>jar</packaging>
  <name>ZonePracOldCombat</name>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <java.version>9</java.version>

    <!-- Runtime dependencies -->
    <bukkit.version>1.13.1-R0.1-SNAPSHOT</bukkit.version>
    <zpp.version>2.4.0</zpp.version>
    <zpp.plugin.version>7.8.3-dev-39-a0522f2</zpp.plugin.version>
    <ocm.version>2.6.0</ocm.version>

    <!-- Build tooling -->
    <compiler.version>3.13.0</compiler.version>
  </properties>

  <!-- Repositories -->
  <repositories>
    <repository>
      <id>spigot-repo</id>
      <url>https://hub.spigotmc.org/nexus/content/groups/public/</url>
    </repository>
    <repository>
      <id>jitpack.io</id>
      <url>https://jitpack.io/</url>
    </repository>
  </repositories>

  <dependencies>
    <!-- API (provided by server) -->
    <dependency>
      <groupId>org.bukkit</groupId>
      <artifactId>bukkit</artifactId>
      <version>${bukkit.version}</version>
      <scope>provided</scope>
    </dependency>
    <!-- API -->
    <dependency>
      <groupId>com.github.sylveya</groupId>
      <artifactId>ZonePracticePro-Api</artifactId>
      <version>${zpp.version}</version>
    </dependency>
    <dependency>
      <groupId>dev.nandi0813</groupId>
      <artifactId>ZonePracticePro</artifactId>
      <version>${zpp.plugin.version}</version>
      <scope>system</scope>
      <systemPath>${project.basedir}/libs/ZonePractice-Pro-${zpp.plugin.version}.jar</systemPath>
    </dependency>
    <dependency>
      <groupId>kernitus.plugin</groupId>
      <artifactId>OldCombatMechanics</artifactId>
      <version>${ocm.version}</version>
      <scope>system</scope>
      <systemPath>${project.basedir}/libs/OldCombatMechanics.jar</systemPath>
    </dependency>
  </dependencies>

  <build>
    <finalName>ZonePracOldCombat-${project.version}</finalName>
    <defaultGoal>clean package</defaultGoal>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${compiler.version}</version>
        <configuration>
          <release>${java.version}</release>
        </configuration>
      </plugin>
    </plugins>
    <resources>
      <resource>
        <directory>src/main/resources</directory>
        <filtering>true</filtering>
      </resource>
    </resources>
  </build>
</project>
