# For optimal out-of-the-box OldCombatMechanics settings,
# copy the contents of example-ocm-config.yml into
# plugins/OldCombatMechanics/config.yml (back up the original first if needed).
# The example file is located in the same folder as this config.yml.

ladder-modes:
  BedWars: old
  SkyWars: old
  Bridges: old
  MLGRush: old
  TNTSumo: old
  BattleRush: old
  Boxing: old
  BuildUHC: old
  Debuff: old
  Nodebuff: old
  PearlFight: old
  Soup: old
  Sumo: old
  SG: old
  Fireball: old
  Spleef: old

modules:
  old:
    - "attack-frequency"
    - "old-armour-durability"
    - "old-fishing-knockback"
    - "fishing-rod-velocity"
    - "projectile-knockback"
    - "disable-crafting"
    - "old-brewing-stand"
    - "disable-enderpearl-cooldown"
    - "disable-attack-cooldown"
    - "disable-sword-sweep"
    - "old-tool-damage"
    - "sword-blocking"
    - "shield-damage-reduction"
    - "old-golden-apples"
    - "old-player-knockback"
    - "old-player-regen"
    - "old-armour-strength"
    - "old-potion-effects"
    - "old-critical-hits"
    - "disable-attack-sounds"
  new: []
